version: '3.8'

services:
  iot_hass_mariadb:
    image: linuxserver/mariadb
    container_name: iot_hass_mariadb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./data/mariadb:/config
    ports:
      - "3306:3306"
    networks:
      - iot_hass_net
  
  iot_hass_adminer:
    image: adminer
    container_name: iot_hass_adminer
    restart: always
    ports:
      - 8895:8080
    depends_on:
      - iot_hass_mariadb
    networks:
      - iot_hass_net
  
  iot_hass_homeassistant:
    image: homeassistant/home-assistant
    container_name: iot_hass_homeassistant
    volumes:
      - ./data/hass-config:/config
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - 8123:8123
    privileged: true
    depends_on:
      - iot_hass_mariadb
      - iot_hass_mqtt
    networks:
      - iot_hass_net
  
  iot_hass_nodered:
    container_name: iot_hass_nodered
    image: nodered/node-red
    ports:
      - "1885:1880"
    volumes:
      - ./data/nodered:/data
    depends_on:
      - iot_hass_homeassistant
      - iot_hass_mqtt
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - iot_hass_net
  
  iot_hass_mqtt:
    image: eclipse-mosquitto
    container_name: iot_hass_mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./data/mosquitto/config:/mosquitto/config"
      - "./data/mosquitto/data:/mosquitto/data"
      - "./data/mosquitto/log:/mosquitto/log"
    env_file:
      - ./.env
    user: "${PUID}:${PGID}"
    networks:
      - iot_hass_net
  
  iot_hass_configurator:
    image: "causticlab/hass-configurator-docker"
    container_name: iot_hass_configurator
    restart: unless-stopped
    ports:
      - "3218:3218/tcp"
    volumes:
      - "./data/configurator-config:/config"
      - "./data/hass-config:/hass-config"
    depends_on:
      - iot_hass_homeassistant
    user: "${PUID}:${PGID}"
    networks:
      - iot_hass_net

networks:
  iot_hass_net:
    driver: bridge