
# Loads default set of integrations. Do not remove.
default_config:
  
# 192.168.0.106 is local host ip
# command for windows: ipconfig /all
# and then Ethernet adapter Ethernet >> IPv4 Address
panel_iframe:
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://192.168.0.106:1885/
    require_admin: true

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
